tunnel: 4a53b7be-1b17-44e0-846f-03882374e54b
credentials-file: /etc/cloudflared/4a53b7be-1b17-44e0-846f-03882374e54b.json

ingress:
  - hostname: minhafinanca.com
    path: /api/.*
    service: http://api:5000

  - hostname: minhafinanca.com
    service: http://frontend:80

  - service: http_status:404

