tunnel: aaa8de64-a202-450d-8695-74ec68117b3a
credentials-file: /etc/cloudflared/aaa8de64-a202-450d-8695-74ec68117b3a.json

ingress:
  - hostname: minhafinanca.com
    path: /api/.*
    service: http://api:5000

  - hostname: minhafinanca.com
    service: http://frontend:80

  - service: http_status:404

